services:
  dice-next:
    image: shiaworkshop/dice-next:latest
    container_name: dice-next
    environment:
      MODE: napcat
    ports:
      - "18088:18088"
    volumes:
      - "${PWD}/config:/app/config"
      - "${PWD}/data:/app/data"
      - "${PWD}/napcat/config:/app/napcat/config"
    networks:
      - dice-next

  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    hostname: dice-next-napcat
    environment:
      MODE: dice
    ports:
      - "6099:6099"
    volumes:
      - "${PWD}/napcat/config:/app/napcat/config"
      - "${PWD}/napcat/QQ_DATA:/app/.config/QQ"
      - "${PWD}/qrcode:/app/napcat/cache"
      - "${PWD}/config:/app/config"
      - "${PWD}/data:/app/data"
    networks:
      - dice-next

networks:
  dice-next:
    driver: bridge
